# Utiliza a imagem oficial do Node.js na fase de build
FROM node:18.16 as build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Instala os  pacotes do Node.js definido no package.json, incluindo o AdonisJS
RUN npm install

# Utiliza a imagem oficial do Node.Js para a fase de execução
FROM node:18.16 as runtime

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de build para o diretório de trabalho
COPY --from=build /app .

# Inicia o aplicativo
CMD [ "npm", "start" ]